### ISSUE TITLE
Got run time error

### ISSUE THREAD

**Issue by DineshKachhot** [cpinan/Cocos2dX_GooglePlayGamesServices#8]
What I am doing is com.carlospinan.utils and com.google.example.games.basegameutils to my app and extends my AppActivity.java with UtilActivity

it compile successful but got run time error Like below

07-28 18:09:22.220: E/AndroidRuntime(23797): FATAL EXCEPTION: main
07-28 18:09:22.220: E/AndroidRuntime(23797): java.lang.ExceptionInInitializerError
07-28 18:09:22.220: E/AndroidRuntime(23797):    at java.lang.Class.newInstanceImpl(Native Method)
07-28 18:09:22.220: E/AndroidRuntime(23797):    at java.lang.Class.newInstance(Class.java:1319)
07-28 18:09:22.220: E/AndroidRuntime(23797):    at android.app.Instrumentation.newActivity(Instrumentation.java:1068)
07-28 18:09:22.220: E/AndroidRuntime(23797):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2015)
07-28 18:09:22.220: E/AndroidRuntime(23797):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2125)
07-28 18:09:22.220: E/AndroidRuntime(23797):    at android.app.ActivityThread.access$600(ActivityThread.java:140)
07-28 18:09:22.220: E/AndroidRuntime(23797):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1227)
07-28 18:09:22.220: E/AndroidRuntime(23797):    at android.os.Handler.dispatchMessage(Handler.java:99)
07-28 18:09:22.220: E/AndroidRuntime(23797):    at android.os.Looper.loop(Looper.java:137)
07-28 18:09:22.220: E/AndroidRuntime(23797):    at android.app.ActivityThread.main(ActivityThread.java:4898)
07-28 18:09:22.220: E/AndroidRuntime(23797):    at java.lang.reflect.Method.invokeNative(Native Method)
07-28 18:09:22.220: E/AndroidRuntime(23797):    at java.lang.reflect.Method.invoke(Method.java:511)
07-28 18:09:22.220: E/AndroidRuntime(23797):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1008)
07-28 18:09:22.220: E/AndroidRuntime(23797):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:775)
07-28 18:09:22.220: E/AndroidRuntime(23797):    at dalvik.system.NativeStart.main(Native Method)
07-28 18:09:22.220: E/AndroidRuntime(23797): Caused by: java.lang.UnsatisfiedLinkError: Couldn't load game: findLibrary returned null
07-28 18:09:22.220: E/AndroidRuntime(23797):    at java.lang.Runtime.loadLibrary(Runtime.java:365)
07-28 18:09:22.220: E/AndroidRuntime(23797):    at java.lang.System.loadLibrary(System.java:535)
07-28 18:09:22.220: E/AndroidRuntime(23797):    at com.carlospinan.utils.UtilActivity.<clinit>(UtilActivity.java:242)
07-28 18:09:22.220: E/AndroidRuntime(23797):    ... 15 more

Where i am doing wrong please help me.

**Comment by cpinan** [comment]
Hi Dinesh,

It looks like you don't have the libraries for cocos2dx embebed.

2015-07-28 7:55 GMT-05:00 DineshKachhot notifications@github.com:

> What I am doing is com.carlospinan.utils and
> com.google.example.games.basegameutils to my app and extends my
> AppActivity.java with UtilActivity
> 
> it compile successful but got run time error Like below
> 
> 07-28 18:09:22.220: E/AndroidRuntime(23797): FATAL EXCEPTION: main
> 07-28 18:09:22.220: E/AndroidRuntime(23797):
> java.lang.ExceptionInInitializerError
> 07-28 18:09:22.220: E/AndroidRuntime(23797): at
> java.lang.Class.newInstanceImpl(Native Method)
> 07-28 18:09:22.220: E/AndroidRuntime(23797): at
> java.lang.Class.newInstance(Class.java:1319)
> 07-28 18:09:22.220: E/AndroidRuntime(23797): at
> android.app.Instrumentation.newActivity(Instrumentation.java:1068)
> 07-28 18:09:22.220: E/AndroidRuntime(23797): at
> android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2015)
> 07-28 18:09:22.220: E/AndroidRuntime(23797): at
> android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2125)
> 07-28 18:09:22.220: E/AndroidRuntime(23797): at
> android.app.ActivityThread.access$600(ActivityThread.java:140)
> 07-28 18:09:22.220: E/AndroidRuntime(23797): at
> android.app.ActivityThread$H.handleMessage(ActivityThread.java:1227)
> 07-28 18:09:22.220: E/AndroidRuntime(23797): at
> android.os.Handler.dispatchMessage(Handler.java:99)
> 07-28 18:09:22.220: E/AndroidRuntime(23797): at
> android.os.Looper.loop(Looper.java:137)
> 07-28 18:09:22.220: E/AndroidRuntime(23797): at
> android.app.ActivityThread.main(ActivityThread.java:4898)
> 07-28 18:09:22.220: E/AndroidRuntime(23797): at
> java.lang.reflect.Method.invokeNative(Native Method)
> 07-28 18:09:22.220: E/AndroidRuntime(23797): at
> java.lang.reflect.Method.invoke(Method.java:511)
> 07-28 18:09:22.220: E/AndroidRuntime(23797): at
> com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1008)
> 07-28 18:09:22.220: E/AndroidRuntime(23797): at
> com.android.internal.os.ZygoteInit.main(ZygoteInit.java:775)
> 07-28 18:09:22.220: E/AndroidRuntime(23797): at
> dalvik.system.NativeStart.main(Native Method)
> 07-28 18:09:22.220: E/AndroidRuntime(23797): Caused by:
> java.lang.UnsatisfiedLinkError: Couldn't load game: findLibrary returned
> null
> 07-28 18:09:22.220: E/AndroidRuntime(23797): at
> java.lang.Runtime.loadLibrary(Runtime.java:365)
> 07-28 18:09:22.220: E/AndroidRuntime(23797): at
> java.lang.System.loadLibrary(System.java:535)
> 07-28 18:09:22.220: E/AndroidRuntime(23797): at
> com.carlospinan.utils.UtilActivity.(UtilActivity.java:242)
> 07-28 18:09:22.220: E/AndroidRuntime(23797): ... 15 more
> 
> Where i am doing wrong please help me.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cpinan/Cocos2dX_GooglePlayGamesServices/issues/8.

## 

Atentamente,

Carlos Eduardo Piñán Indacochea.
Ingeniero de sistemas.
